# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bullz And Bearz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bullz And Bearz
  pod "Alamofire"
  pod "SVProgressHUD"
  pod "SwiftyJSON"
  pod "CDAlertView"
  pod "SAConfettiView"

end
