//
//  Words.swift
//  Bullz And Bearz
//

import Foundation

let warren = ["We simply attempt to be fearful when others are greedy and to be greedy only when others are fearful.", "Price is what you pay. Value is what you get.", "Someone's sitting in the shade today because someone planted a tree a long time ago.", "Risk comes from not knowing what you're doing.", "It's only when the tide goes out that you discover who's been swimming naked.", "Beware of geeks bearing formulas.", "Our favorite holding period is forever."]
let elon = ["I always invest my own money in the companies that I create. I don't believe in the whole thing of just using other people's money. I don't think that's right. I'm not going to ask other people to invest in something if I'm not prepared to do so myself.", "I'm interested in things that change the world or that affect the future and wondrous, new technology where you see it, and you're like, 'Wow, how did that even happen? How is that possible?."]
let peter = ["The trick is not to learn to trust your gut feelings, but rather to discipline yourself to ignore them. Stand by your stocks as long as the fundamental story of the company hasn’t changed.", "Whenever you invest in any company, you’re looking for its market cap to rise. This can’t happen unless buyers are paying higher prices for the shares, making your investment more valuable.", "People who succeed in the stock market also accept periodic losses, setbacks, and unexpected occurrences. Calamitous drops do not scare them out of the game.", "If you can follow only one bit of data, follow the earnings—assuming the company in question has earnings. As you’ll see in this text, I subscribe to the crusty notion that sooner or later earnings make or break an investment in equities. What the stock price does today, tomorrow, or next week is only a distraction."]
let steve = ["Deciding what not to do is as important as deciding what to do.", "Quality is much better than quantity. One home run is much better than two doubles.", "Things don't have to change the world to be important."]
let bill = ["If I believe that I am right, I will take it to the end of the earth until I am proven right.", "In order to be successful, you have to make sure that being rejected doesn’t bother you at all.", "Short-term market and economic prognostication is largely a fool’s errand, we invest according to a strategy that makes the need to rely on short-term market or economic assessments largely irrelevant.", "You can learn investing by reading books."]
let mark = ["Sweat equity is the most valuable equity there is. Know your business and industry better than anyone else in the world. Love what you do or don't do it.", "What I've learned in these 11 years is you just got to stay focused and believe in yourself and trust your own ability and judgment.", "The number-one job of the hedge-fund manager is not to make sure that you can retire with a smile on your face - it's for him to retire with a smile on his face.", "I still work hard to know my business. I'm continuously looking for ways to improve all my companies, and I'm always selling. Always."]
